# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78379eb9ded199904d17b60d5de4313b900ed2354911b46517765535ae5c8e65e0cf43b08e3a40660cbeb56ccbb17850c5236edd3d34b7f37c42ac89a8b3d430

test:
  secret_key_base: 5f75d3f858832d7e25110729ab5126ff7d00d6123fd5bc237e8af5321402e3c2d3ff9b66ee6c03669d06c13054564fb3c0ea371918ac21363dac8444195b56c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
